### ISSUE TITLE
The title number format in the destination.docx has been changed, could keep it previously

### ISSUE THREAD

**Issue by lichao10424** [ryanpierson/merge_docx#2]
The title number format in the destination.docx has been changed, could keep it previously
two changed point: 
1) the number string (1.1 --> 1.); 
2) the indentation position
template.docx
1	测试用例
1.1	测试用例1

destination.docx
1.	测试用例
        1.	测试用例1

**Comment by ryanpierson** [comment]
I just added support to maintain list numbering format in the merge. As far as I understand your problem I believe you'll see the result you're expecting now.
